version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/hashicorp/terraform-plugin-sdk/v2
    versions:
    - 2.4.0
    - 2.4.2
    - 2.4.4
