name: Bump Git Version
on:
  push:
    branches:
      - main
jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagging.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      id: tagging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
